
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=Daniel

###

GET http://localhost:3000/posts/674df9fd01eff817a54fedad

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "owner": "Daniel",
    "content": "Hello World..."
}
###

PUT  http://localhost:3000/posts/674dfecd927634c2b2381c38
Content-Type: application/json

{
    "title": "Hello Again",
    "owner": "Daniel",
    "content": "Hello World... update"
}
###

DELETE http://localhost:3000/posts/674df9fd01eff817a54fedad